### PR TITLE
Shiny Apps Rmd file

### PR DESCRIPTION
**Pull request by nathcarter**

### CODE REVIEW

**Review by rosseji — CHANGES_REQUESTED** [review]
to run on the site, you need to render the markdown file to generate a html page.

```
blogdown::render_site()
```

**Review by rosseji — CHANGES_REQUESTED** [review]
once more... see the check netlify deploy link

**Comment by rosseji** [comment]
great, index looks good.

app doesn't seem to work in the test deploy?

**Comment by nathcarter** [comment]
Yes, I'm not surprised, I think it's because the Shiny apps have to be running off the server, rather than built in the space. I don't really know.

**Comment by rosseji** [comment]
screenshot then?

**Comment by rosseji** [comment]
what happened there ^ ?

**Comment by nathcarter** [comment]
@rosseji I'd failed to test some stuff in the deploy checks, hopefully it might work now.

**Comment by rosseji** [comment]
It stills looks like this for me:

screen shot 2017-06-01 at 2 16 02 pm

**Comment by nathcarter** [comment]
Yep, working on embedding issues now.

**Comment by nathcarter** [comment]
Put a preview image in as well, so even if it doesn't work post-deployment, the preview is there.

**Review by rosseji — APPROVED** [review]

**Comment by rosseji** [comment]
cool, looks great

**Comment by rosseji** [comment]
you might need to branch again from the master and redo it in one commit because it can't compile all these commits for some reason

**Pull request closed without merging**
